name: finance_house_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  dio: ^5.7.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  youtube_player_iframe: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  mockito: ^5.4.2
  test: ^1.21.0


flutter:

  uses-material-design: true
  assets:
    - assets/
